source 'http://rubygems.org'

gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'mime-types'
gem 'rake'
gem 'cucumber'
gem 'allure-cucumber'
gem 'browserstack-local'
gem 'parallel_tests'
gem 'pry'
gem 'nokogiri', '~> 1.12', '>= 1.12.5'
gem 'solargraph', '~> 0.44.2'
gem 'webdrivers', '~> 5.0'