
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            docker-machine start
            docker-machine env
            eval "$(docker-machine env default)"
            docker pull homebrew/brew:3.3.8
            brew install allure
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
