
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run: ruby --version
             gem install bundler
             bundle install
             bundle exec rake