
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e cross browser
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
