
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run: ruby --version
      - run : gem install bundler
      - run : bundle install
      - run : bundle exec rake