
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            curl -o allure-2.13.8.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz
            sudo tar -zxvf allure-2.13.8.tgz -C /opt/
            sudo ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure
            allure --version
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
