
version: 2
orbs:
  macos: circleci/macos@1.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            sudo apt-get install allure
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
