
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            sudo apt-add-repository ppa:qameta/allure
            sudo apt-get update 
            sudo apt-get install allure
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
