
version: 2
jobs:
  build:
    docker:
      - image: homebrew/brew:3.3.8
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            brew install ruby@2.7
            echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/ruby@2.7/bin:$PATH"' >> ~/.profile
            source ~/.profile
            ruby --version
            gem install bundler:2.2.22
      - run:
          name: generate report 
          command: |
            brew install allure
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
