
version: 2
jobs:
  build:
    docker:
      - image: jolive/rbrew:latest
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            allure generate report/allure-results/ --clean

      - store_artifacts:
          path: report/allure-results/
      - store_artifacts:
          path: allure-report/
