
version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/Livestorm_Technical_Test
    docker:
      # this is important to use proper image with browsers support
      - image: adiniz/rubywd
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_DB: capybara-circleci
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: capybara-circleci
      - image: redis:3.2.7
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Cucumber 
          command: |
            bundle exec rake
      # Save test results for timing analysis
      - store_test_results:
          path: ~/report/allure-results
      - store_artifacts:
          path: ~/report/allure-results
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 17 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build

   all_commits:
       jobs:
           - build:
               filters:
                   branches:
                       ignore:
                           - developer
                           - test