
version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            curl -L https://github.com/allure-framework/allure2/releases/download/<< parameters.version >>/allure-commandline-<< parameters.version >>.zip -o /tmp/allure.zip
            unzip /tmp/allure.zip
            sudo mv allure-<< parameters.version >> /usr/local/share/allure/bin/allure
            allure serve report/allure-results/
      - store_artifacts:
          path: report/allure-results/
