
version: 2
jobs:
  build:
    docker:
      - image: jolive/rbrew:1.0.0
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler:2.2.22
            bundle install;
            bundle exec rake
      - run:
          name: generate report 
          command: |
            brew -v
            allure generate report/allure-results/ --clean

      - store_artifacts:
          path: report/allure-results/
      - store_artifacts:
          path: allure-report/
