version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3
      - image: homebrew/brew:3.3.8
    steps:
      - checkout
      - run:
          name: e2e tests
          command: |
            ruby --version;
            gem install bundler;
            bundle install;
            bundle exec rake
      - run:
          name: generate report
          command: |
            brew install allure
            allure generate report/allure-results/ --clean
      - store_artifacts:
          path: report/allure-results/
      - store_artifacts:
          path: allure-report/