server: hub-cloud.browserstack.com
user: jolivgilberth1
key: Dzi5E3v8hYqszXVskn2j

common_caps:
  build: capybara-browserstack
  browserstack.debug: true

browser_caps:
- browser: chrome
- browser: firefox
- browser: internet explorer
- browser: safari
