server: hub-cloud.browserstack.com
user: chastityrastogi_Ly0KMx
key: XAQ9ssNxyiqykaiyTnhy

common_caps:
  build: livestorm-technical-test
  browserstack.debug: true

browser_caps:
- browser: chrome
- browser: safari
